# Generated by Django 4.2.15 on 2024-08-16 21:36

from django.db import migrations, models
import django.db.models.deletion
import newsfeed.models


class Migration(migrations.Migration):

    dependencies = [
        ('newsfeed', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='News',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to=newsfeed.models._author_directory_path)),
                ('title', models.CharField(max_length=30)),
                ('description', models.CharField(max_length=100, verbose_name='desc')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='newsfeed.user')),
            ],
        ),
    ]
