# Generated by Django 5.1 on 2024-08-18 18:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newsfeed', '0003_comment'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='username',
            field=models.CharField(default='DEFAULT USERNAME', max_length=100),
        ),
    ]
